### ISSUE TITLE
Undefined method omniauth_authorize_path

### ISSUE THREAD

**Issue by naps62** [zamith/citygate#2]
The error occurs in this view file: https://github.com/zamith/citygate/blob/master/app/views/devise/shared/_links.erb

The fix, or at least the one that worked for me:

replace:

```
    omniauth_authorize_path(resource_name, provider)
```

with

```
    user_omniauth_authorize_path(provider)
```

**Comment by zamith** [comment]
Could not reproduce, please be more specific on how you got to the error. If possible provide a test that breaks.

Thanks.

**Comment by naps62** [comment]
this repo is where it broke: https://github.com/luismiranda/tipster
delete its app/views/devise folder to reproduce

On Fri, Nov 16, 2012 at 10:05 AM, Luís Ferreira notifications@github.comwrote:

> Could not reproduce, please be more specific on how you got to the error.
> If possible provide a test that breaks.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zamith/citygate/issues/2#issuecomment-10442189.

## 

Cumprimentos
Miguel Palhas

**Comment by zamith** [comment]
Please provide a test where this breaks.

**Comment by eklipse2k8** [comment]
undefined method `omniauth_authorize_path' for #<#Class:0x007fc09abe5868:0x007fc09e71b860>

20: 
21: <%- if devise_mapping.omniauthable? %>
22:   <%- resource_class.omniauth_providers.each do |provider| %>
23:     <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
24:   <% end -%>
25: <% end -%>

**Comment by eklipse2k8** [comment]
I'm seeing this issue as well, any idea?

**Comment by zamith** [comment]
Have you tried the proposed solution to use `user_omniauth_authorize_path(provider)` instead?

**Comment by eklipse2k8** [comment]
Oh ok, yup, fixing the template worked... heh, sorry about that :-)

**Comment by zamith** [comment]
@eklipse2k8 Awesome. ;)

**Comment by zamith** [comment]
@eklipse2k8 Are you using citygate on any project? I'm rounding up some projects that use it, to put on the README, would it be ok to put yours?

**Comment by hoangdd** [comment]
I got same error, and i fix it by don't use config/initializers/omniauth.rb and add provider config to config/initializers/devise.rb

config.omniauth :github, 'APP_ID', 'APP_SECRET'

**Comment by yagudaev** [comment]
It may also occur if your provider is missing from the initializers list. So don't forget to uncomment:

```
config.omniauth :facebook, CONFIG[:facebook_key], CONFIG[:facebook_secret]
```

**Comment by svegaca** [comment]
I write a helper method for fix this error without override views:

```
  def omniauth_authorize_path(resource_name, provider)
    send "#{resource_name}_omniauth_authorize_path", provider
  end
```

It works for me :)

**Comment by christiangenco** [comment]
+1

**Comment by justinschier** [comment]
I started getting this error today (Jul 27, 2016) when I upgraded to Ruby 2.3.1 and Rails 4.2.7. The solution that worked for me was to change all instances of `user_omniauth_authorize_path(:twitter)` to `user_twitter_omniauth_authorize_path`.

**Comment by Yager47** [comment]
Maybe you forgot to add `:omniauthable` option to devise in user model

```
class User < ActiveRecord::Base
  devise :omniauthable, ...

end
```

**Comment by 1Rhino** [comment]
@justinschier Thank you. It worked. (Ruby 2.3.1 and rails 4.2.7)
Pattern: `user_RESOURCE_NAME_omniauth_authorize_path`
example: `user_twitter_omniauth_authorize_path` or `user_google_oauth2_omniauth_authorize_path`

**Comment by awesome** [comment]
```
# config/routes.rb

devise_scope :user do
  get '/users/auth/:provider', to: "omniauth_callbacks#%{provider}", as: :user_omniauth_authorize
end
```

use with either: `user_omniauth_authorize_path(:twitter)` or `user_omniauth_authorize_url(:twitter)`
